### ISSUE TITLE
Proposiciones logicas

### ISSUE THREAD

**Issue by Alondra-oss** [SistemasTecTlaxiaco/actividad-7-proposiciones-l-gicas-Alondra-oss#1]
[PROPOSICIONES LOGICASs.pdf](https://github.com/user-attachments/files/17445691/PROPOSICIONES.LOGICASs.pdf)

**Comment by Eddi3mendoz** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Calificación: 20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
